### ISSUE TITLE
Munge Failed - Slurm

### ISSUE THREAD

**Issue by juani-ig** [dun/munge#125] opened 2022-09-08 17:43 UTC
Hi all!

I can't start munge on the compute nodes.

# systemctl restart munge
Job for munge.service failed because the control process exited with error code.
See "systemctl status munge.service" and "journalctl -xe" for details.

# systemctl status munge.service
● munge.service - MUNGE authentication service
   Loaded: loaded (/usr/lib/systemd/system/munge.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2022-09-08 19:37:10 CEST; 1min 8s ago
     Docs: man:munged(8)
  Process: 24304 ExecStart=/usr/sbin/munged (code=exited, status=1/FAILURE)

Sep 08 19:37:10 cn5.cluster.local systemd[1]: Starting MUNGE authentication service...
Sep 08 19:37:10 cn5.cluster.local systemd[1]: munge.service: Control process exited, code=exited status=1
Sep 08 19:37:10 cn5.cluster.local systemd[1]: munge.service: Failed with result 'exit-code'.
Sep 08 19:37:10 cn5.cluster.local systemd[1]: Failed to start MUNGE authentication service.

# journalctl -xe
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- The unit munge.service has entered the 'failed' state with result 'exit-code'.
Sep 08 19:37:10 cn5.cluster.local systemd[1]: Failed to start MUNGE authentication service.
-- Subject: Unit munge.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit munge.service has failed.
-- 
-- The result is failed.

# ls -la /etc/munge/munge.key 
-r-------- 1 munge munge 1024 Sep  8 19:11 /etc/munge/munge.key

I have copied the munge.key from master node , too

Thanks!
Kind regards.

**Comment by dun** [comment] 2022-09-08 18:55
I can't tell from the above output what the problem is. You need to locate the `munged` error message. It should look like:
`munged: Error: something something something`

Check the installation guide for tips on [checking the log](../wiki/Installation-Guide#check-the-log). If you're still unable to locate the error message, run `munged` [in the foreground](../wiki/Installation-Guide#run-the-daemon-in-the-foreground) to have log messages written to stderr. You should be able to find the error message towards the end of that output.

**Comment by dun** [comment] 2022-09-15 16:28
Closing this since it's been a week with no follow-up. Please post the error message if you're still having problems.

**Closed by dun** 2022-09-15 16:28 UTC
Labels: question
